steps:
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - gcloud
#   - workflows
#   - deploy
#   - myFirstWorkflow
#   - --source=myfirstworkflow.yaml
#   - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
#   # - --service-account=baseball-434300@appspot.gserviceaccount.com
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - retrosheet_fetcher
  - --region=us-central1
  - --source=./retrosheet_fetcher
  - --trigger-http
  - --runtime=python311
  - --entry-point=fetch_file
  - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
  - --run-service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - gcloud
#   - functions
#   - deploy
#   - sample_function_2
#   - --region=us-central1
#   - --source=./bigquery_loader
#   - --trigger-http
#   - --runtime=python311
#   - --entry-point=hello_content
#   - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
#   - --run-service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - gcloud
#   - functions
#   - deploy
#   - load_people
#   - --region=us-central1
#   - --source=./bigquery_loader
#   - --trigger-http
#   - --runtime=python311
#   - --entry-point=load_people
#   - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
#   - --run-service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
#   - --memory=512MB
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - gcloud
#   - functions
#   - deploy
#   - load_ballparks
#   - --region=us-central1
#   - --source=./bigquery_loader
#   - --trigger-http
#   - --runtime=python311
#   - --entry-point=load_ballparks
#   - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
#   - --run-service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - gcloud
#   - functions
#   - deploy
#   - load_teams
#   - --region=us-central1
#   - --source=./bigquery_loader
#   - --trigger-http
#   - --runtime=python311
#   - --entry-point=load_teams
#   - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
#   - --run-service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - workflows
  - deploy
  - refresh_workflow
  - --source=refresh_workflow.yaml
  - --service-account=baseball-prod@baseball-434918.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY