steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - workflows
  - deploy
  - myFirstWorkflow
  - --source=myfirstworkflow.yaml
  - --service-account=baseball-prod@baseball-434300.iam.gserviceaccount.com
  # - --service-account=baseball-434300@appspot.gserviceaccount.com
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - services
  - disable
  - cloudfunctions.googleapis.com
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - services
  - enable
  - cloudfunctions.googleapis.com
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - sleep
  - '60'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - sample_function
  - --region=us-central1
  - --source=./sample_function
  - --trigger-http
  - --runtime=python311
  - --entry-point=hello_get
  - --service-account=baseball-prod@baseball-434300.iam.gserviceaccount.com
  - --run-service-account=baseball-prod@baseball-434300.iam.gserviceaccount.com
  # - --service-account=baseball-434300@appspot.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY